import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, CloudUpload, Gauge } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ECU Tuning Files Online | Professional File Service | AK Cloud',
  description: 'Order ECU tuning files online through a professional workflow for workshops and tuners. Upload your ORI, specify the request and receive the modified file in AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/tuning-files-online', languages: { en: '/en/ecu-file-service/tuning-files-online', es: '/ecu-file-service/tuning-files-online', 'x-default': '/ecu-file-service/tuning-files-online' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Gauge size={14}/> ECU TUNING FILES · ONLINE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">ECU tuning files online.<br/><span className="text-[#ff425a]">From original read to delivered MOD.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">A digital file service workflow for professional workshops and tuners. Send the original ECU read with the vehicle, ECU and requested calibration information and manage the complete technical request through AK Cloud.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/remote" className="ak-v5-button-secondary">Remote file service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><CloudUpload className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Online request workflow</h2><p className="mt-3 leading-7 text-white/45">Upload the ORI and technical details without separating files, messages and job information across different channels.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Professional delivery history</h2><p className="mt-3 leading-7 text-white/45">Keep the original file, requirements, support and delivered modified file connected to the same request.</p></div></div></section></main>
}