import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Gauge, FileUp } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Diesel ECU Tuning File Service | AK Cloud',
  description: 'Professional diesel ECU tuning file service for workshops and tuners. Upload the original ECU read and manage performance calibration requests through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/diesel-tuning', languages: { en: '/en/ecu-file-service/diesel-tuning', es: '/ecu-file-service/diesel-tuning', 'x-default': '/ecu-file-service/diesel-tuning' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Gauge size={14}/> DIESEL ECU TUNING · FILE SERVICE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Diesel ECU tuning files.<br/><span className="text-[#ff425a]">Professional calibration workflow.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">For workshops and tuners working with diesel engine management. Upload the original ECU read, identify the exact vehicle, engine, ECU and software and submit the required performance calibration through one structured AK Cloud job.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/performance-tuning" className="ak-v5-button-secondary">Performance tuning</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Exact original file</h2><p className="mt-3 leading-7 text-white/45">Vehicle, engine, ECU identification, software and read method are submitted together with the ORI for technical evaluation.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Clear ORI to MOD workflow</h2><p className="mt-3 leading-7 text-white/45">Request details, technical communication and the delivered modified file remain linked to the same job.</p></div></div></section></main>
}