import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, FileUp, Wrench } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ECU Tuning File Supplier for Workshops | AK Cloud',
  description: 'ECU tuning file supplier for professional workshops and tuners. Upload original ECU files, job details and calibration requirements through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/tuning-file-supplier', languages: { en: '/en/ecu-file-service/tuning-file-supplier', 'x-default': '/en/ecu-file-service/tuning-file-supplier' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Wrench size={14}/> ECU TUNING FILE SUPPLIER · WORKSHOPS</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">ECU tuning files for workshops.<br/><span className="text-[#ff425a]">A supplier workflow designed around real jobs.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">AK Cloud is designed for professional workshops and tuners that need a clear ECU tuning file supply workflow. Send the original ECU read with vehicle identification, ECU details, read method and calibration requirements, then keep the technical exchange and delivered file connected to the job.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service" className="ak-v5-button-secondary">ECU File Service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Complete job information</h2><p className="mt-3 leading-7 text-white/45">Upload the ORI and provide the ECU, software, vehicle configuration and requested result so the technical request has the right context.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Professional file delivery</h2><p className="mt-3 leading-7 text-white/45">Requests, support communication and delivered files stay grouped by job for a cleaner day-to-day workshop process.</p></div></div></section></main>
}