'use client'

import { useEffect, useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import { Building2, CheckCircle2, Clock3, Mail, MapPin, Phone, RefreshCw, Search, ShieldAlert, UserCheck, Wrench, XCircle } from 'lucide-react'
import AppShell from '@/components/AppShell'

type Solicitud=any; type Plan=any; type Distribuidor=any

export default function DistribuidoresPage(){
  const [solicitudes,setSolicitudes]=useState<Solicitud[]>([]); const [planes,setPlanes]=useState<Plan[]>([]); const [distribuidores,setDistribuidores]=useState<Distribuidor[]>([]); const [selected,setSelected]=useState<Solicitud|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('pendiente'); const [planId,setPlanId]=useState(''); const [creditos,setCreditos]=useState(50); const [motivo,setMotivo]=useState('')
  async function load(){setLoading(true);try{const res=await fetch('/api/ak-cloud/distribuidores',{cache:'no-store'});const json=await res.json();if(!res.ok)throw new Error(json.error);setSolicitudes(json.solicitudes||[]);setPlanes(json.planes||[]);setDistribuidores(json.distribuidores||[])}catch(e:any){toast.error(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const filtered=useMemo(()=>solicitudes.filter(s=>(filter==='todas'||s.estado===filter)&&[s.empresa,s.nombre,s.email,s.nif,s.ciudad].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[solicitudes,filter,query])
  async function action(action:string){if(!selected)return;setSaving(true);try{const res=await fetch('/api/ak-cloud/distribuidores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,action,plan_id:planId||null,creditos_iniciales:creditos,motivo})});const json=await res.json();if(!res.ok)throw new Error(json.error);toast.success(action==='aprobar'?'Distribuidor aprobado':'Solicitud actualizada');setSelected(null);setMotivo('');await load()}catch(e:any){toast.error(e.message)}finally{setSaving(false)}}
  const stats={pendientes:solicitudes.filter(s=>s.estado==='pendiente').length,info:solicitudes.filter(s=>s.estado==='informacion_solicitada').length,aprobadas:solicitudes.filter(s=>s.estado==='aprobada').length,activos:distribuidores.filter(d=>d.estado==='activo').length}
  return <AppShell><div className="space-y-6"><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-center"><div><p className="text-xs font-black uppercase tracking-[.24em] text-red-400">AK Cloud CRM</p><h1 className="mt-2 text-4xl font-black">Distribuidores</h1><p className="mt-2 text-zinc-500">Revisa solicitudes, asigna plan y activa cuentas del portal.</p></div><button onClick={load} className="btn btn-dark inline-flex items-center gap-2"><RefreshCw size={17}/>Actualizar</button></div>
  <div className="grid gap-4 md:grid-cols-4">{[[stats.pendientes,'Pendientes',Clock3],[stats.info,'Piden revisión',ShieldAlert],[stats.aprobadas,'Aprobadas',CheckCircle2],[stats.activos,'Activos',UserCheck]].map(([v,l,I]:any)=><div className="card p-5" key={l}><I className="text-red-400"/><p className="mt-4 text-3xl font-black">{v}</p><p className="text-xs font-black uppercase tracking-wider text-zinc-500">{l}</p></div>)}</div>
  <div className="grid gap-5 2xl:grid-cols-[1fr_430px]"><section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-zinc-800 p-5 md:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl border border-zinc-800 bg-black/30 px-4"><Search size={17} className="text-zinc-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Empresa, email, NIF..." className="w-full border-0 bg-transparent"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-zinc-800 bg-black px-4"><option value="pendiente">Pendientes</option><option value="informacion_solicitada">Información solicitada</option><option value="aprobada">Aprobadas</option><option value="rechazada">Rechazadas</option><option value="todas">Todas</option></select></div><div className="divide-y divide-zinc-800">{loading?<div className="p-8 text-zinc-500">Cargando...</div>:filtered.length===0?<div className="p-8 text-zinc-500">No hay solicitudes.</div>:filtered.map(s=><button key={s.id} onClick={()=>{setSelected(s);setPlanId(s.plan_id||planes.find(p=>p.destacado)?.id||planes[0]?.id||'');setCreditos(s.creditos_iniciales||50);setMotivo(s.motivo_estado||'')}} className={`grid w-full gap-3 p-5 text-left transition hover:bg-white/[.03] md:grid-cols-[1fr_220px_130px] ${selected?.id===s.id?'bg-red-500/5':''}`}><div><p className="font-black text-white">{s.empresa}</p><p className="mt-1 text-sm text-zinc-500">{s.nombre} {s.apellidos||''} · {s.email}</p></div><div className="text-sm text-zinc-400">{s.ciudad||'—'}, {s.pais||'—'}<br/>{s.especialidad||'Sin especialidad'}</div><Status estado={s.estado}/></button>)}</div></section>
  <aside className="card p-5">{!selected?<div className="grid min-h-[420px] place-items-center text-center text-zinc-500"><div><Building2 className="mx-auto mb-4" size={42}/><p>Selecciona una solicitud para revisarla.</p></div></div>:<div><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-red-400">Solicitud</p><h2 className="mt-1 text-2xl font-black">{selected.empresa}</h2></div><Status estado={selected.estado}/></div><div className="mt-5 space-y-3 text-sm">{[[Mail,selected.email],[Phone,selected.telefono],[MapPin,[selected.direccion,selected.ciudad,selected.provincia,selected.pais].filter(Boolean).join(', ')],[Wrench,`${selected.especialidad||'—'} · ${(selected.herramientas||[]).join(', ')||'Sin herramientas'}`]].map(([I,v]:any)=><div className="flex gap-3 rounded-xl border border-zinc-800 bg-black/25 p-3" key={String(v)}><I size={17} className="mt-0.5 text-red-400"/><span className="text-zinc-300">{v||'—'}</span></div>)}</div>{selected.estado!=='aprobada'&&<><label className="mt-5 block text-xs font-black uppercase text-zinc-500">Plan inicial<select value={planId} onChange={e=>setPlanId(e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-800 bg-black p-3 text-white">{planes.map(p=><option value={p.id} key={p.id}>{p.nombre} · {p.precio_mensual} €/mes</option>)}</select></label><label className="mt-4 block text-xs font-black uppercase text-zinc-500">Créditos de bienvenida<input type="number" min="0" value={creditos} onChange={e=>setCreditos(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-zinc-800 bg-black p-3 text-white"/></label><label className="mt-4 block text-xs font-black uppercase text-zinc-500">Mensaje / motivo<textarea value={motivo} onChange={e=>setMotivo(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-zinc-800 bg-black p-3 text-white"/></label><div className="mt-5 grid gap-2"><button disabled={saving} onClick={()=>action('aprobar')} className="btn btn-red inline-flex justify-center gap-2"><CheckCircle2 size={17}/>Aprobar y activar</button><button disabled={saving} onClick={()=>action('solicitar_informacion')} className="btn btn-dark inline-flex justify-center gap-2"><ShieldAlert size={17}/>Solicitar información</button><button disabled={saving} onClick={()=>action('rechazar')} className="btn btn-dark inline-flex justify-center gap-2 text-red-300"><XCircle size={17}/>Rechazar</button></div></>}</div>}</aside></div></div></AppShell>
}
function Status({estado}:any){const c:any={pendiente:'bg-amber-500/10 text-amber-300 border-amber-500/25',aprobada:'bg-emerald-500/10 text-emerald-300 border-emerald-500/25',rechazada:'bg-red-500/10 text-red-300 border-red-500/25',informacion_solicitada:'bg-sky-500/10 text-sky-300 border-sky-500/25'};return <span className={`inline-flex h-fit w-fit rounded-full border px-3 py-1 text-[10px] font-black uppercase ${c[estado]||c.pendiente}`}>{String(estado).replace('_',' ')}</span>}
