import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Gauge, Settings2 } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Turbo Petrol ECU Tuning File Service | AK Cloud',
  description: 'Turbo petrol ECU tuning file service for professional workshops and tuners. Submit the original ECU read, hardware setup and performance target through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/turbo-petrol-tuning' },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Gauge size={14}/> TURBO PETROL · ECU FILE SERVICE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Turbo petrol ECU tuning files.<br/><span className="text-[#ff425a]">Built around the real vehicle setup.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">For professional turbo petrol calibration requests. Upload the original ECU read and provide the exact engine, ECU, software, read method, fuel, turbo and relevant hardware configuration for technical evaluation.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/petrol-tuning" className="ak-v5-button-secondary">Petrol tuning</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><Settings2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Hardware-aware request</h2><p className="mt-3 leading-7 text-white/45">Turbo, fueling, intake, exhaust and other relevant changes can be documented with the ORI so the request reflects the actual vehicle.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Professional file workflow</h2><p className="mt-3 leading-7 text-white/45">ORI, technical requirements, communication and delivered MOD stay organised inside the same AK Cloud job.</p></div></div></section></main>
}