import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Wrench, FileUp } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ECU File Service for Garages | AK Cloud',
  description: 'ECU file service for garages and automotive workshops. Upload the original ECU read, vehicle information and job requirements through the AK Cloud workflow.',
  alternates: { canonical: '/en/ecu-file-service/garages', languages: { en: '/en/ecu-file-service/garages', 'x-default': '/en/ecu-file-service/garages' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Wrench size={14}/> GARAGES · ECU FILE SERVICE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">ECU file service for garages.<br/><span className="text-[#ff425a]">A simpler way to manage tuning jobs.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">AK Cloud is designed for garages that need a clear professional workflow for ECU file requests. Submit the original read, vehicle and ECU information, requested work and relevant job details without relying on fragmented email or messaging threads.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service" className="ak-v5-button-secondary">ECU File Service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Upload the job once</h2><p className="mt-3 leading-7 text-white/45">Keep the ORI file, vehicle data, ECU identification, requirements and supporting information linked to one request.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Built for workshop workflow</h2><p className="mt-3 leading-7 text-white/45">Technical communication and delivered files remain organised around the job, helping garages manage customer work more clearly.</p></div></div></section></main>
}