import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, FileUp, SlidersHorizontal } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Custom ECU Tuning Files for Professionals | AK Cloud',
  description: 'Custom ECU tuning files for professional workshops and tuners. Upload the original ECU read and job requirements through the AK Cloud file service.',
  alternates: { canonical: '/en/ecu-file-service/custom-tuning-files', languages: { en: '/en/ecu-file-service/custom-tuning-files', 'x-default': '/en/ecu-file-service/custom-tuning-files' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><SlidersHorizontal size={14}/> CUSTOM ECU TUNING FILES · PROFESSIONALS</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Custom ECU tuning files.<br/><span className="text-[#ff425a]">Built around the vehicle and the job.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">AK Cloud gives professional workshops and tuners a structured way to request custom ECU tuning files. Upload the original ECU read with vehicle, ECU, software, read method and calibration requirements so each request arrives with the technical context needed for the job.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service" className="ak-v5-button-secondary">ECU File Service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Send the original file</h2><p className="mt-3 leading-7 text-white/45">Attach the ORI together with the vehicle and ECU identification and describe the requested calibration clearly.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Job-based delivery</h2><p className="mt-3 leading-7 text-white/45">Keep the request, technical exchange and delivered calibration connected to the same workshop job inside AK Cloud.</p></div></div></section></main>
}