import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, FileCode2, Workflow } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ECU Remapping Files Online | AK Cloud',
  description: 'Professional ECU remapping files online for workshops and tuners. Send the original ECU read and manage the calibration request through the AK Cloud file service.',
  alternates: { canonical: '/en/ecu-file-service/remapping-files' },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><FileCode2 size={14}/> ECU REMAPPING FILES · ONLINE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">ECU remapping files online.<br/><span className="text-[#ff425a]">A file service workflow for professional tuners.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">Submit ECU remapping requests without scattering files and technical details across different channels. Upload the ORI, provide the vehicle and ECU information, describe the requested calibration and manage the delivered MOD through AK Cloud.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/remap" className="ak-v5-button-secondary">ECU remap service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileCode2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Original file first</h2><p className="mt-3 leading-7 text-white/45">Every remapping request starts from the original ECU read plus the technical context required to assess the job.</p></div><div className="ak-v5-card p-6"><Workflow className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Traceable professional workflow</h2><p className="mt-3 leading-7 text-white/45">Vehicle data, requirements, support and the delivered modified file remain organised under the same request.</p></div></div></section></main>
}