import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Gauge, FileUp } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Car ECU Tuning File Service | AK Cloud',
  description: 'Car ECU tuning file service for professional workshops and tuners. Upload the original ECU read and manage performance calibration requests through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/car-tuning' },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Gauge size={14}/> CAR ECU TUNING · FILE SERVICE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Car ECU tuning file service.<br/><span className="text-[#ff425a]">Professional calibration requests in one workflow.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">For workshops and tuners handling passenger-car ECU calibration jobs. Upload the original ECU file, identify the vehicle and control unit, specify the required tuning and keep the complete request organised in AK Cloud.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/performance-tuning" className="ak-v5-button-secondary">Performance tuning</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Vehicle and ECU context</h2><p className="mt-3 leading-7 text-white/45">Submit the original read together with vehicle, ECU, software, read method and relevant hardware information for technical evaluation.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Designed for professional file work</h2><p className="mt-3 leading-7 text-white/45">The ORI, tuning request, support conversation and delivered MOD stay linked to the same job.</p></div></div></section></main>
}