import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, FileUp, Workflow } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ECU Tuning File Provider for Professionals | AK Cloud',
  description: 'Professional ECU tuning file provider for workshops and tuners. Submit original ECU reads and job data through the structured AK Cloud file service workflow.',
  alternates: { canonical: '/en/ecu-file-service/tuning-file-provider', languages: { en: '/en/ecu-file-service/tuning-file-provider', 'x-default': '/en/ecu-file-service/tuning-file-provider' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Workflow size={14}/> ECU TUNING FILE PROVIDER · PROFESSIONAL</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">An ECU tuning file provider.<br/><span className="text-[#ff425a]">Built for professional workshop workflows.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">AK Cloud provides workshops and professional tuners with a structured way to request ECU tuning files. Upload the original read, identify the vehicle and ECU, add the relevant technical data and keep each request, conversation and delivered file linked to the same job.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service" className="ak-v5-button-secondary">ECU File Service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Submit the original ECU read</h2><p className="mt-3 leading-7 text-white/45">Vehicle, ECU, software, read method and requested calibration data remain attached to the file-service request.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Track every tuning job</h2><p className="mt-3 leading-7 text-white/45">Keep technical communication and delivered files organised in one professional workflow instead of scattered across messages and attachments.</p></div></div></section></main>
}