'use client'
import Link from 'next/link'
import { Bell, Command, Menu, Plus, Search } from 'lucide-react'
import AKSidebar from './AKSidebar'
export default function AKPageShell({children,title,subtitle,eyebrow='AK Cloud',actions}:{children:React.ReactNode,title?:string,subtitle?:string,eyebrow?:string,actions?:React.ReactNode}){
 return <main className="ak-v5-bg flex min-h-screen text-white"><AKSidebar/><section className="relative z-10 min-w-0 flex-1">
  <header className="ak-v5-topbar sticky top-0 z-40 flex min-h-[76px] items-center justify-between px-4 lg:px-7"><div className="flex min-w-0 items-center gap-3"><button className="grid h-11 w-11 place-items-center rounded-[14px] border border-white/[.08] bg-white/[.035] lg:hidden"><Menu size={19}/></button><div className="hidden h-11 min-w-[360px] items-center gap-3 rounded-[14px] border border-white/[.075] bg-white/[.03] px-4 text-sm text-white/30 md:flex"><Search size={17}/><span>Buscar pedido, ECU, HW, SW...</span><span className="ml-auto flex items-center gap-1 rounded-lg border border-white/[.08] px-2 py-1 text-[10px]"><Command size={11}/> K</span></div></div><div className="flex items-center gap-2"><Link href="/nuevo-pedido" className="ak-v5-button !px-4 !py-2.5 text-xs"><Plus size={16}/> Nuevo servicio</Link><Link href="/notificaciones" className="relative grid h-11 w-11 place-items-center rounded-[14px] border border-white/[.08] bg-white/[.035] text-white/60"><Bell size={18}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-[#e5a05d] shadow-[0_0_12px_rgba(229,160,93,.9)]"/></Link></div></header>
  <div className="relative mx-auto max-w-[1680px] p-4 sm:p-6 lg:p-8 xl:p-10">{(title||subtitle)&&<div className="mb-9 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="ak-v5-kicker">{eyebrow}</div>{title&&<h1 className="ak-v5-title mt-4 text-4xl sm:text-5xl xl:text-6xl">{title}</h1>}{subtitle&&<p className="mt-4 max-w-3xl text-sm leading-7 text-white/40">{subtitle}</p>}</div>{actions}</div>}<div className="ak-v5-reveal">{children}</div></div>
 </section></main>
}