import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, FileCode2, Workflow } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ECU Tuning Files for Workshops | AK Cloud',
  description: 'ECU tuning files for professional workshops and tuners through AK Cloud. Upload the original ECU read and manage each calibration request in one organised workflow.',
  alternates: { canonical: '/en/ecu-file-service/tuning-files' },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><FileCode2 size={14}/> ECU TUNING FILES · WORKSHOPS & TUNERS</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">ECU tuning files for workshops.<br/><span className="text-[#ff425a]">A structured file service for professional jobs.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">AK Cloud provides a dedicated workflow for professional ECU tuning file requests. Upload the original read, identify the vehicle and ECU, describe the required calibration and keep the delivered file linked to the job.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/custom-tuning" className="ak-v5-button-secondary">Custom tuning</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileCode2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">From ORI to delivered file</h2><p className="mt-3 leading-7 text-white/45">Each request starts from the original ECU read and the technical information supplied by the workshop or tuner.</p></div><div className="ak-v5-card p-6"><Workflow className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Built for repeat file work</h2><p className="mt-3 leading-7 text-white/45">Requests, vehicle data, technical context, support and delivered files stay organised instead of being scattered across separate conversations.</p></div></div></section></main>
}