import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, FileUp, Gauge } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ECU Remap Files | Professional File Service | AK Cloud',
  description: 'Professional ECU remap files for workshops and tuners. Upload the original ECU read, submit the calibration requirements and manage the job through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/ecu-remap-files', languages: { en: '/en/ecu-file-service/ecu-remap-files', 'x-default': '/en/ecu-file-service/ecu-remap-files' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Gauge size={14}/> ECU REMAP FILES · PROFESSIONAL</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Professional ECU remap files.<br/><span className="text-[#ff425a]">A workflow built for workshops and tuners.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">Upload the original ECU file, identify the vehicle and control unit and describe the required calibration. AK Cloud keeps the technical request, communication and delivered modified file organised around the same job.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service" className="ak-v5-button-secondary">ECU File Service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Submit the original ECU read</h2><p className="mt-3 leading-7 text-white/45">Add vehicle, ECU, reading method, hardware and tuning requirements so the request contains the technical information needed for evaluation.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Keep each remap organised</h2><p className="mt-3 leading-7 text-white/45">ORI, request details, support and delivered MOD stay linked to one professional job history.</p></div></div></section></main>
}