import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Cpu, FileUp } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Bosch EDC17 File Service for Professionals | AK Cloud',
  description: 'Professional Bosch EDC17 file service for workshops and tuners. Upload the original ECU file and manage your tuning file request through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/edc17', languages: { en: '/en/ecu-file-service/edc17', es: '/ecu-file-service/edc17', 'x-default': '/ecu-file-service/edc17' } },
}

export default function Page(){return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Cpu size={14}/> BOSCH EDC17 · FILE SERVICE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Bosch EDC17 file service.<br/><span className="text-[#ff425a]">For workshops and professional tuners.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">AK Cloud provides a structured workflow for professional EDC17 file requests. Upload your original read, provide the exact vehicle, engine, ECU hardware and software information and keep the delivered modified file linked to the job.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service" className="ak-v5-button-secondary">ECU File Service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Correct original read</h2><p className="mt-3 leading-7 text-white/45">The exact read method and available solution depend on the ECU variant, protocol and software.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Job-based delivery</h2><p className="mt-3 leading-7 text-white/45">Keep ORI, request information, communication and MOD associated with the same order.</p></div></div></section></main>