import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Gauge, Settings2 } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Turbo Diesel ECU Tuning File Service | AK Cloud',
  description: 'Turbo diesel ECU tuning file service for professional workshops and tuners. Upload the original ECU read, vehicle data and hardware configuration through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/turbo-diesel-tuning' },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Gauge size={14}/> TURBO DIESEL · ECU FILE SERVICE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Turbo diesel ECU tuning files.<br/><span className="text-[#ff425a]">Structured for professional calibration work.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">For workshops and tuners handling turbo diesel performance requests. Submit the original ECU read with exact vehicle, engine, ECU, software, read method and relevant hardware information for technical evaluation.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/diesel-tuning" className="ak-v5-button-secondary">Diesel tuning</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><Settings2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Exact setup information</h2><p className="mt-3 leading-7 text-white/45">Document the ECU identification, turbo, fueling and other relevant hardware together with the original read and requested target.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">ORI to MOD in one job</h2><p className="mt-3 leading-7 text-white/45">Technical details, support conversation and the delivered modified file remain linked to the same AK Cloud workflow.</p></div></div></section></main>
}