import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Wrench, Settings2 } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ECU Tuning File Service for Tuners | AK Cloud',
  description: 'ECU tuning file service for professional tuners. Send original ECU files, technical requirements and vehicle information through the organised AK Cloud workflow.',
  alternates: { canonical: '/en/ecu-file-service/tuning-for-tuners' },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Wrench size={14}/> ECU TUNING FILES · FOR TUNERS</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">ECU tuning files for tuners.<br/><span className="text-[#ff425a]">Send the ORI. Keep the job organised.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">A professional file service workflow for tuners handling ECU calibration jobs. Submit the original read, vehicle and ECU identification, read method, hardware details and requested calibration in one structured request.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/custom-tuning" className="ak-v5-button-secondary">Custom tuning</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><Settings2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Structured tuning requests</h2><p className="mt-3 leading-7 text-white/45">Keep ECU identification, vehicle configuration, hardware and calibration targets together instead of splitting technical information across channels.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">ORI to MOD traceability</h2><p className="mt-3 leading-7 text-white/45">The original file, request, support conversation and delivered modified file remain associated with the same tuning job.</p></div></div></section></main>
}