import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Gauge, FileUp } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Petrol ECU Tuning Files | Professional File Service | AK Cloud',
  description: 'Petrol ECU tuning files for professional workshops and tuners. Upload the original ECU read and manage performance calibration requests through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/petrol-tuning-files', languages: { en: '/en/ecu-file-service/petrol-tuning-files', 'x-default': '/en/ecu-file-service/petrol-tuning-files' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Gauge size={14}/> PETROL ECU · TUNING FILES</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Petrol ECU tuning files.<br/><span className="text-[#ff425a]">Professional calibration workflow.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">For workshops and tuners working with petrol engine management systems. Upload the original ECU read, provide accurate vehicle and ECU identification, hardware information and the requested performance target for technical evaluation.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service" className="ak-v5-button-secondary">ECU File Service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><FileUp className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Accurate petrol ECU requests</h2><p className="mt-3 leading-7 text-white/45">Submit the ORI together with ECU identification, read method, engine configuration, hardware changes and requested calibration.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Everything linked to the job</h2><p className="mt-3 leading-7 text-white/45">Original file, technical requirements, support and delivered MOD remain organised inside the same AK Cloud workflow.</p></div></div></section></main>
}