import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, FileUp, Gauge, ShieldCheck } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Stage 1 File Service for Professional Tuners | AK Cloud',
  description: 'Professional Stage 1 file service for workshops and tuners. Upload your ORI and manage the calibration request and MOD delivery through AK Cloud.',
  alternates: { canonical: '/en/stage-1-file-service', languages: { en: '/en/stage-1-file-service', es: '/stage-1-file-service', 'x-default': '/stage-1-file-service' } },
}

export default function Page(){return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex">STAGE 1 · PROFESSIONAL FILE SERVICE</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Stage 1 tuning files.<br/><span className="text-[#ff425a]">Built around your professional workflow.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">Read the original ECU file with your compatible tool, submit the vehicle and ECU information and manage the Stage 1 request through AK Cloud. The ORI, job communication and delivered MOD stay connected to the same order.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service" className="ak-v5-button-secondary">ECU File Service</Link></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[['Upload ORI',FileUp],['Request Stage 1',Gauge],['Receive MOD',ShieldCheck]].map(([t,I]:any)=><div key={t} className="ak-v5-card p-6"><I size={21} className="text-[#67e8d1]"/><h2 className="mt-4 font-bold">{t}</h2></div>)}</div></section><section className="border-t border-white/[.06]"><div className="mx-auto max-w-[1180px] px-5 py-16"><div className="flex items-center gap-3 text-white/50"><CheckCircle2 className="text-[#67e8d1]"/> Pay per file. No credit pack required to start.</div></div></section></main>