import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Gauge, Settings2 } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Stage 3 ECU Tuning Files | Professional File Service | AK Cloud',
  description: 'Stage 3 ECU tuning files for professional workshops and tuners with modified vehicles. Submit the ORI and full hardware specification through AK Cloud.',
  alternates: { canonical: '/en/ecu-file-service/stage-3-tuning-files', languages: { en: '/en/ecu-file-service/stage-3-tuning-files', 'x-default': '/en/ecu-file-service/stage-3-tuning-files' } },
}

export default function Page() {
  return <main className="ak-v5-bg min-h-screen text-white"><header className="ak-v5-topbar"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4"><Link href="/" className="text-sm font-black tracking-[.18em]">AK <span className="text-[#ff425a]">CLOUD</span></Link><Link href="/register" className="ak-v5-button !px-4 !py-2.5 text-xs">Create account <ArrowRight size={15}/></Link></div></header><section className="mx-auto max-w-[1180px] px-5 py-24"><div className="ak-v5-pill inline-flex"><Gauge size={14}/> STAGE 3 · ECU TUNING FILES</div><h1 className="ak-v5-title mt-7 max-w-5xl text-5xl sm:text-7xl">Stage 3 ECU tuning files.<br/><span className="text-[#ff425a]">For serious hardware configurations.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/50">A professional file service workflow for modified vehicles requiring hardware-specific calibration requests. Upload the original ECU read and document turbo, fueling, intake, exhaust and other relevant modifications for technical evaluation.</p><div className="mt-9 flex gap-3"><Link href="/register" className="ak-v5-button">Request access <ArrowRight size={18}/></Link><Link href="/en/ecu-file-service/custom-tuning" className="ak-v5-button-secondary">Custom tuning</Link></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="ak-v5-card p-6"><Settings2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Hardware-specific information</h2><p className="mt-3 leading-7 text-white/45">Provide the complete setup so the request can be assessed around the real vehicle configuration instead of a generic calibration.</p></div><div className="ak-v5-card p-6"><CheckCircle2 className="text-[#67e8d1]"/><h2 className="mt-4 text-xl font-bold">Professional job history</h2><p className="mt-3 leading-7 text-white/45">ORI, specifications, support conversation and delivered MOD stay connected to the same request inside AK Cloud.</p></div></div></section></main>
}